/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QKART_SANITY_LOGIN.Module1;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.concurrent.TimeUnit;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.WindowType;
import org.openqa.selenium.remote.BrowserType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class QkartSanity {

    public static String lastGeneratedUserName;


    public static RemoteWebDriver createDriver() throws MalformedURLException {
        // Launch Browser using Zalenium
        final DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setBrowserName(BrowserType.CHROME);
        RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:8082/wd/hub"), capabilities);

        return driver;
    }

    public static void logStatus(String type, String message, String status) {

        System.out.println(String.format("%s |  %s  |  %s | %s", String.valueOf(java.time.LocalDateTime.now()), type,
                message, status));
    }

    public static void takeScreenshot(WebDriver driver, String screenshotType, String description) {

        try{
            File file = new File("/screenshots");
            if(!file.exists()) {
                file.mkdirs();
            }
            String timestamp = String.valueOf(java.time.LocalDateTime.now()).replace(":", ".");
            String fileName = String.format("screenshot_%s_%s_%s.png", timestamp, screenshotType, description);

            TakesScreenshot scrShot = ((TakesScreenshot) driver);
            File srcfile = scrShot.getScreenshotAs(OutputType.FILE);
            File destfile = new File("screenshots/" +fileName);
            FileUtils.copyFile(srcfile, destfile);
        } catch (Exception e) {
            e.printStackTrace();
        }
        // TODO: CRIO_TASK_MODULE_SYNCHRONISATION - Implement method using below steps
        /*
         * 1. Check if the folder "/screenshots" exists, create if it doesn't
         * 2. Generate a unique string using the timestamp
         * 3. Capture screenshot
         * 4. Save the screenshot inside the "/screenshots" folder using the following
         * naming convention: screenshot_<Timestamp>_<ScreenshotType>_<Description>.png
         * eg: screenshot_2022-03-05T06:59:46.015489_StartTestcase_Testcase01.png
         */
    }

    /*
     * Testcase01: Verify the functionality of Login button on the Home page
     */
    public static Boolean TestCase01(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver, "StartTestCase", "Testcase01");
        Boolean status;
        logStatus("Start TestCase", "Test Case 1: Verify User Registration", "DONE");

        // Visit the Registration page and register a new user
        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("TestCase 1", "Test Case Pass. User Registration Pass", "FAIL");
            logStatus("End TestCase", "Test Case 1: Verify user Registration : ", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestCaseFailure", "Testcase01");

            // Return False as the test case Fails
            return false;
        } else {
            logStatus("TestCase 1", "Test Case Pass. User Registration Pass", "PASS");
        }

        // Save the last generated username
        lastGeneratedUserName = registration.lastGeneratedUsername;

        // Visit the login page and login with the previuosly registered user
        Login login = new Login(driver);
        login.navigateToLoginPage();
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        logStatus("Test Step", "User Perform Login: ", status ? "PASS" : "FAIL");
        if (!status) {
            logStatus("End TestCase", "Test Case 1: Verify user Registration : ", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestCaseFailure", "Testcase01");
            return false;
        }

        // Visit the home page and log out the logged in user
        Home home = new Home(driver);
        status = home.PerformLogout();
        logStatus("End TestCase", "Test Case 1: Verify user Registration : ", status ? "PASS" : "FAIL");

        takeScreenshot(driver, "EndTestCase", "Testcase01");

        return status;
    }

    /*
     * Verify that an existing user is not allowed to re-register on QKart
     */
    public static Boolean TestCase02(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver, "StartTestCase", "Testcase02");
        Boolean status;
        logStatus("Start Testcase", "Test Case 2: Verify User Registration with an existing username ", "DONE");

        // Visit the Registration page and register a new user
        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        logStatus("Test Step", "User Registration : ", status ? "PASS" : "FAIL");
        if (!status) {
            logStatus("End TestCase", "Test Case 2: Verify user Registration : ", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestCaseFailure", "Testcase02");
            return false;

        }

        // Save the last generated username
        lastGeneratedUserName = registration.lastGeneratedUsername;

        // Visit the Registration page and try to register using the previously
        // registered user's credentials
        registration.navigateToRegisterPage();
        status = registration.registerUser(lastGeneratedUserName, "abc@123", false);

        // If status is true, then registration succeeded, else registration has
        // failed. In this case registration failure means Success
        logStatus("End TestCase", "Test Case 2: Verify user Registration : ", status ? "FAIL" : "PASS");
        takeScreenshot(driver, "EndTestCase", "Testcase02");
        return !status;
    }

    /*
     * Verify the functinality of the search text box
     */
    public static Boolean TestCase03(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver, "StartTestCase", "Testcase03");
        logStatus("TestCase 3", "Start test case : Verify functionality of search box ", "DONE");
        boolean status;

        // Visit the home page
        Home homePage = new Home(driver);
        homePage.navigateToHome();

        // SLEEP_STMT_01 : Wait for Page to Load
        //Thread.sleep(5000);

        // Search for the "yonex" product
        status = homePage.searchForProduct("yonex");
        if (!status) {
            logStatus("TestCase 3", "Test Case Failure. Unable to search for given product", "FAIL");
            takeScreenshot(driver, "TestCaseFailure", "Testcase03");
            return false;
        }

        // Fetch the search results
        List<WebElement> searchResults = homePage.getSearchResults();

        // Verify the search results are available
        if (searchResults.size() == 0) {
            logStatus("TestCase 3", "Test Case Failure. There were no results for the given search string", "FAIL");
            takeScreenshot(driver, "TestCaseFailure", "Testcase03");
            return false;
        }

        for (WebElement webElement : searchResults) {
            // Create a SearchResult object from the parent element
            SearchResult resultelement = new SearchResult(webElement);

            // Verify that all results contain the searched text
            String elementText = resultelement.getTitleofResult();
            if (!elementText.toUpperCase().contains("YONEX")) {
                logStatus("TestCase 3", "Test Case Failure. Test Results contains un-expected values: " + elementText,
                        "FAIL");
                        takeScreenshot(driver, "TestCaseFailure", "Testcase03");
                return false;
            }
        }

        logStatus("Step Success", "Successfully validated the search results ", "PASS");
        // SLEEP_STMT_02
        Thread.sleep(2000);

        // Search for product
        status = homePage.searchForProduct("Gesundheit");
        if (!status) {
            logStatus("TestCase 3", "Test Case Failure. Unable to search for given product", "FAIL");
            takeScreenshot(driver, "TestCasefailure", "Testcase03");
            return false;
        }

        // Verify no search results are found
        searchResults = homePage.getSearchResults();
        if (searchResults.size() == 0) {
            if (homePage.isNoResultFound()) {
                logStatus("Step Success", "Successfully validated that no products found message is displayed", "PASS");
            }
            logStatus("TestCase 3", "Test Case PASS. Verified that no search results were found for the given text",
                    "PASS");
        } else {
            logStatus("TestCase 3", "Test Case Fail. Expected: no results , actual: Results were available", "FAIL");
            takeScreenshot(driver, "TestCaseFailure", "Testcase03");
            return false;
        }
        takeScreenshot(driver, "EndTestCase", "Testcase03");
        return true;
    }

    /*
     * Verify the presence of size chart and check if the size chart content is as
     * expected
     */
    public static Boolean TestCase04(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver, "StartTestCase", "Testcase04");
        logStatus("TestCase 4", "Start test case : Verify the presence of size Chart", "DONE");
        boolean status = false;

        // Visit home page
        Home homePage = new Home(driver);
        homePage.navigateToHome();

        // SLEEP_STMT_03 : Wait for page to load
        Thread.sleep(5000);

        // Search for product and get card content element of search results
        status = homePage.searchForProduct("Running Shoes");
        List<WebElement> searchResults = homePage.getSearchResults();

        // Create expected values
        List<String> expectedTableHeaders = Arrays.asList("Size", "UK/INDIA", "EU", "HEEL TO TOE");
        List<List<String>> expectedTableBody = Arrays.asList(Arrays.asList("6", "6", "40", "9.8"),
                Arrays.asList("7", "7", "41", "10.2"), Arrays.asList("8", "8", "42", "10.6"),
                Arrays.asList("9", "9", "43", "11"), Arrays.asList("10", "10", "44", "11.5"),
                Arrays.asList("11", "11", "45", "12.2"), Arrays.asList("12", "12", "46", "12.6"));

        // Verify size chart presence and content matching for each search result
        for (WebElement webElement : searchResults) {
            SearchResult result = new SearchResult(webElement);

            // Verify if the size chart exists for the search result
            if (result.verifySizeChartExists()) {
                logStatus("Step Success", "Successfully validated presence of Size Chart Link", "PASS");

                // Verify if size dropdown exists
                status = result.verifyExistenceofSizeDropdown(driver);
                logStatus("Step Success", "Validated presence of drop down", status ? "PASS" : "FAIL");
                takeScreenshot(driver, "TestCaseFailure", "Testcase04");

                // Open the size chart
                if (result.openSizechart()) {
                    // Verify if the size chart contents matches the expected values
                    if (result.validateSizeChartContents(expectedTableHeaders, expectedTableBody, driver)) {
                        logStatus("Step Success", "Successfully validated contents of Size Chart Link", "PASS");
                    } else {
                        logStatus("Step Failure", "Failure while validating contents of Size Chart Link", "FAIL");
                    }

                    // Close the size chart modal
                    status = result.closeSizeChart(driver);

                } else {
                    logStatus("TestCase 4", "Test Case Fail. Failure to open Size Chart", "FAIL");
                    takeScreenshot(driver, "TestCaseFailure", "Testcase04");
                    return false;
                }

            } else {
                logStatus("TestCase 4", "Test Case Fail. Size Chart Link does not exist", "FAIL");
                takeScreenshot(driver, "TestCaseFailure", "Testcase04");
                return false;
            }
        }
        logStatus("TestCase 4", "Test Case PASS. Validated Size Chart Details", "PASS");
        takeScreenshot(driver, "EndTestCase", "Testcase04");
        return status;
    }

    /*
     * Verify the complete flow of checking out and placing order for products is
     * working correctly
     */
    public static Boolean TestCase05(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver, "StartTestCase", "Testcase05");
        Boolean status;
        logStatus("Start TestCase", "Test Case 5: Verify Happy Flow of buying products", "DONE");

        // Go to the Register page
        Register registration = new Register(driver);
        registration.navigateToRegisterPage();

        // Register a new user
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("TestCase 5", "Test Case Failure. Happy Flow Test Failed", "FAIL");
            takeScreenshot(driver, "TestCaseFailure", "Testcase05");
        }

        // Save the username of the newly registered user
        lastGeneratedUserName = registration.lastGeneratedUsername;

        // Go to the login page
        Login login = new Login(driver);
        login.navigateToLoginPage();

        // Login with the newly registered user's credentials
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        if (!status) {
            logStatus("Step Failure", "User Perform Login Failed", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestCaseFailure", "Testcase05");
            logStatus("End TestCase", "Test Case 5: Happy Flow Test Failed : ", status ? "PASS" : "FAIL");
        }

        // Go to the home page
        Home homePage = new Home(driver);
        homePage.navigateToHome();

        // Find required products by searching and add them to the user's cart
        status = homePage.searchForProduct("Yonex");
        homePage.addProductToCart("YONEX Smash Badminton Racquet");
        status = homePage.searchForProduct("Tan");
        homePage.addProductToCart("Tan Leatherette Weekender Duffle");

        // Click on the checkout button
        homePage.clickCheckout();

        // Add a new address on the Checkout page and select it
        Checkout checkoutPage = new Checkout(driver);
        checkoutPage.addNewAddress("Addr line 1 addr Line 2 addr line 3");
        checkoutPage.selectAddress("Addr line 1 addr Line 2 addr line 3");

        // Place the order
        checkoutPage.placeOrder();
        // SLEEP_STMT_04: Wait for place order to succeed and navigate to Thanks page
        try {
            WebDriverWait wait = new WebDriverWait(driver, 10);
            wait.until(ExpectedConditions.urlToBe("https://crio-qkart-frontend-qa.vercel.app/thanks"));

        } catch(Exception e) {
            return false;
        }
        // WebDriverWait wait = new WebDriverWait(driver, 10);
        // wait.until(ExpectedConditions.urlToBe("https://crio-qkart-frontend-qa.vercel.app/thanks"));
        //Thread.sleep(3000);

        // Check if placing order redirected to the Thansk page
        status = driver.getCurrentUrl().endsWith("/thanks");

        // Go to the home page
        homePage.navigateToHome();
        //Thread.sleep(3000);

        // Log out the user
        homePage.PerformLogout();

        logStatus("End TestCase", "Test Case 5: Happy Flow Test Completed : ", status ? "PASS" : "FAIL");
        takeScreenshot(driver, "EndTestCase", "Testcase05");
        return status;
    }

    /*
     * Verify the quantity of items in cart can be updated
     */
    public static Boolean TestCase06(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver, "StartTestCase", "Testcase06");
        Boolean status;
        logStatus("Start TestCase", "Test Case 6: Verify that cart can be edited", "DONE");
        Register registration = new Register(driver);
        registration.navigateToRegisterPage();

        // Register a new user
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("TestCase 5", "Test Case Failure. Happy Flow Test Failed", "FAIL");
            takeScreenshot(driver, "TestCaseFailure", "Testcase06");
        }

        // Save the username of the newly registered user
        lastGeneratedUserName = registration.lastGeneratedUsername;

        // Go to the login page
        Login login = new Login(driver);
        login.navigateToLoginPage();

        // Login with the newly registered user's credentials
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        if (!status) {
            logStatus("Step Failure", "User Perform Login Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase", "Test Case 5: Happy Flow Test Failed : ", status ? "PASS" : "FAIL");
            takeScreenshot(driver, "TestCaseFailure", "Testcase06");
        }

        // Go to the home page
        Home homePage = new Home(driver);

        // TODO: Add "Xtend Smart Watch" to cart
        homePage.navigateToHome();
        homePage.searchForProduct("Xtend Smart Watch");
        homePage.addProductToCart("Xtend Smart Watch");
        

        // TODO: Add "Yarine Floor Lamp" to cart
        homePage.searchForProduct("Yarine Floor Lamp");
        homePage.addProductToCart("Yarine Floor Lamp");
        Thread.sleep(2000);
        // update watch quantity to 2
        homePage.changeProductQuantityinCart("Xtend Smart Watch", 2);

        // update table lamp quantity to 0
        homePage.changeProductQuantityinCart("Yarine Floor Lamp", 0);

        // update watch quantity again to 1
        homePage.changeProductQuantityinCart("Xtend Smart Watch", 1);

        homePage.clickCheckout();

        Checkout checkoutPage = new Checkout(driver);
        checkoutPage.addNewAddress("Addr line 1 addr Line 2 addr line 3");
        checkoutPage.selectAddress("Addr line 1 addr Line 2 addr line 3");

        checkoutPage.placeOrder();
        Thread.sleep(3000);

        status = driver.getCurrentUrl().endsWith("/thanks");

        homePage.navigateToHome();
        Thread.sleep(3000);
        homePage.PerformLogout();

        logStatus("End TestCase", "Test Case 6: Verify that cart can be edited: ", status ? "PASS" : "FAIL");
        takeScreenshot(driver, "EndTestCase", "Testcase06");
        return status;
    }


    public static Boolean TestCase07(RemoteWebDriver driver) throws InterruptedException {
        Boolean status;
        logStatus("Start TestCase",
                "Test Case 7: Verify that insufficient balance error is thrown when the wallet balance is not enough",
                "DONE");

        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("Step Failure", "User Perform Registration Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 7: Verify that insufficient balance error is thrown when the wallet balance is not enough: ",
                    status ? "PASS" : "FAIL");
            return false;
        }
        lastGeneratedUserName = registration.lastGeneratedUsername;

        Login login = new Login(driver);
        login.navigateToLoginPage();
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        if (!status) {
            logStatus("Step Failure", "User Perform Login Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 7: Verify that insufficient balance error is thrown when the wallet balance is not enough: ",
                    status ? "PASS" : "FAIL");
            return false;
        }

        Home homePage = new Home(driver);
        homePage.navigateToHome();
        status = homePage.searchForProduct("Stylecon");
        homePage.addProductToCart("Stylecon 9 Seater RHS Sofa Set");
        Thread.sleep(3000);

        homePage.changeProductQuantityinCart("Stylecon 9 Seater RHS Sofa Set", 10);

        homePage.clickCheckout();

        Checkout checkoutPage = new Checkout(driver);
        checkoutPage.addNewAddress("Addr line 1 addr Line 2 addr line 3");
        checkoutPage.selectAddress("Addr line 1 addr Line 2 addr line 3");

        checkoutPage.placeOrder();
        Thread.sleep(3000);

        status = checkoutPage.verifyInsufficientBalanceMessage();

        logStatus("End TestCase",
                "Test Case 7: Verify that insufficient balance error is thrown when the wallet balance is not enough: ",
                status ? "PASS" : "FAIL");

        return status;
    }

    public static Boolean TestCase08(RemoteWebDriver driver) throws InterruptedException {
        Boolean status = false;
        logStatus("Start TestCase","Test Case 8: Add Test Case for Multitab Scenario","DONE");
        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("Step Failure", "User Perform Registration Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 8: Add Test Case for Multitab Scenario: ",
                    status ? "PASS" : "FAIL");
            return false;
        }
        lastGeneratedUserName = registration.lastGeneratedUsername;

        Login login = new Login(driver);
        login.navigateToLoginPage();
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        if (!status) {
            logStatus("Step Failure", "User Perform Login Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 8: Add Test Case for Multitab Scenario: ",
                    status ? "PASS" : "FAIL");
            return false;
        }

        Home homePage = new Home(driver);
        homePage.navigateToHome();
        //String url = driver.getCurrentUrl();
        String parent = driver.getWindowHandle();
        status = homePage.searchForProduct("Yonex");
        homePage.addProductToCart("YONEX Smash Badminton Racquet");
        List<String> actualproductlist = ProductList(driver);
        Thread.sleep(3000);


        driver.switchTo().newWindow(WindowType.TAB);
        System.out.println(driver.getCurrentUrl());
        driver.get("https://crio-qkart-frontend-qa.vercel.app/");
        login.navigateToLoginPage();
        login.PerformLogin(lastGeneratedUserName, "abc@123");

        Set<String> windowhandles = driver.getWindowHandles();
        List<String> windowhandleslist = new ArrayList<>(windowhandles);
        driver.switchTo().window(windowhandleslist.get(1));

        if(ProductList(driver).containsAll(actualproductlist)) {
            status = true;
        }
        driver.close();
        Thread.sleep(2000);
        driver.switchTo().window(parent);

        logStatus("End TestCase",
                "Test Case 8: Add Test Case for Multitab Scenario: ",
                status ? "PASS" : "FAIL");

        // TODO: CRIO_TASK_MODULE_SYNCHRONISATION -
        return status;
        
    }
    public static List<String> ProductList(WebDriver driver) {
        List<WebElement> tempproductelementlist = driver.findElements(By.xpath("//*[@id='root']/div/div/div[3]/div[2]/div/div/div/div[2]/div[1]"));
        List<String> tempproductlist = new ArrayList<String>();
        for (WebElement tempwebelement : tempproductelementlist) {
            tempproductlist.add(tempwebelement.getText());
            
        }
        return tempproductlist;
    }

    public static Boolean TestCase9(RemoteWebDriver driver) throws InterruptedException {

        // TODO: CRIO_TASK_MODULE_SYNCHRONISATION -
        Boolean status = false;
        logStatus("Start TestCase","Test Case 9: Verify Privacy Policy and Terms of Service","DONE");
        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("Step Failure", "User Perform Registration Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 9: Verify Privacy Policy and Terms of Service: ",
                    status ? "PASS" : "FAIL");
            return false;
        }
        lastGeneratedUserName = registration.lastGeneratedUsername;

        Login login = new Login(driver);
        login.navigateToLoginPage();
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        if (!status) {
            logStatus("Step Failure", "User Perform Login Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 9: Verify Privacy Policy and Terms of Service: ",
                    status ? "PASS" : "FAIL");
            return false;
        }

        Home homePage = new Home(driver);
        homePage.navigateToHome();
        String url = driver.getCurrentUrl();
        String parent = driver.getWindowHandle();
        
        WebElement privacypolicylink = driver.findElement(By.xpath("//a[text()='Privacy policy']"));
        privacypolicylink.click();
        if(url.equalsIgnoreCase(driver.getCurrentUrl())) {
            status = true;
        } else {
            status = false;
        }
    
        Set<String> windowHandles = driver.getWindowHandles();
        List<String> windowHandlesList = new ArrayList<>(windowHandles);
        driver.switchTo().window(windowHandlesList.get(1));
        WebElement privacypolicytext = driver.findElement(By.xpath("//h2[text()='Privacy Policy']"));
        privacypolicytext.getText().equalsIgnoreCase("Privacy Policy");
        // pp content 
        Thread.sleep(3000);
        driver.close();

        driver.switchTo().window(parent);

        WebElement termsofservicelink = driver.findElement(By.xpath("//a[text()='Terms of Service']"));
        termsofservicelink.click();
        if(url.equalsIgnoreCase(driver.getCurrentUrl())) {
            status = true;
        } else {
            status = false;
        }

        Set<String> windowHandles1 = driver.getWindowHandles();
        List<String> windowHandlesList1 = new ArrayList<>(windowHandles1);
        driver.switchTo().window(windowHandlesList1.get(1));
        WebElement termsofservicetext = driver.findElement(By.xpath("//h2[text()='Terms of Service']"));
        termsofservicetext.getText().equalsIgnoreCase("Terms of Service");
        Thread.sleep(3000);
        driver.close();
        driver.switchTo().window(parent);

        // String termsofservice = driver.getWindowHandle();
        // driver.switchTo().window(termsofservice);
        // Thread.sleep(3000);

       // driver.switchTo().window(parent);

        //Set<String> allWindows = driver.getWindowHandles();
        //for(String window : allWindows) {
            //if(!window.equalsIgnoreCase(parent) && !window.equalsIgnoreCase(termsofservice)) {
                ///
            //     driver.switchTo().window(window);
            //     Thread.sleep(3000);
            //     if(driver.findElement(By.xpath("//h2[text()='Privacy Policy']")).getText().equalsIgnoreCase("Privacy Policy")) {
            //         status = true;
            //     } else {
            //         status = false;
            //     }
            // }
            //driver.switchTo().window(privacypolicy);
            // if(!window.equalsIgnoreCase(parent) && !window.equalsIgnoreCase(privacypolicy)) {
            //     driver.switchTo().window(window);
            //     Thread.sleep(3000);
            //     if(driver.findElement(By.xpath("//h2[text()='Terms of Service']")).getText().equalsIgnoreCase("Terms Of Service")) {
            //         status = true;
            //     } else {
            //         status = false;
            //     }
                
            // }

        // }
        // driver.switchTo().window(parent);
        // WebElement termsofservicelink = driver.findElement(By.xpath("//a[text()='Terms of Service']"));
        // termsofservicelink.click();
        // Thread.sleep(3000);
        // if(url.equalsIgnoreCase(driver.getCurrentUrl())) {
        //     status = true;
        // } else {
        //     status = false;
        // }
        // Set<String> allWindows1 = driver.getWindowHandles();
        // for(String window : allWindows1) {
        //     if(!window.equalsIgnoreCase(parent)) {
        //         driver.switchTo().window(window);
        //         Thread.sleep(3000);
        //         if(driver.findElement(By.xpath("//h2[text()='Terms of Service']")).getText().equalsIgnoreCase("Terms Of Service")) {
        //             status = true;
        //         } else {
        //             status = false;
        //         }
        //     }

        // }

        logStatus("End TestCase",
                "Test Case 9: Verify Privacy Policy and Terms of Service: ",
                status ? "PASS" : "FAIL");
       // logStatus("End TestCase", "Test Case 9: Verify Privacy Policy and Terms of Service:", status: "PASS");


        return status;
    }

    public static Boolean TestCase10(RemoteWebDriver driver) throws InterruptedException {
        Boolean status = false;
        logStatus("Start TestCase","Test Case 10: Verify Contact Us Link","DONE");
        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("Step Failure", "User Perform Registration Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 10: Verify Contact Us Link: ",
                    status ? "PASS" : "FAIL");
            return false;
        }
        lastGeneratedUserName = registration.lastGeneratedUsername;

        Login login = new Login(driver);
        login.navigateToLoginPage();
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        if (!status) {
            logStatus("Step Failure", "User Perform Login Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 10: Verify Contact Us Link: ",
                    status ? "PASS" : "FAIL");
            return false;
        }

        Home homePage = new Home(driver);
        homePage.navigateToHome();
        WebElement contactuslink = driver.findElement(By.xpath("//*[@id='root']/div/div/div[5]/div[2]/p[3]"));
        contactuslink.click();
        Thread.sleep(3000);
        WebElement nameelm = driver.findElement(By.xpath("//input[@placeholder='Name']"));
        nameelm.sendKeys("crio user");
        WebElement emailelm =driver.findElement(By.xpath("//input[@placeholder='Email']"));
        emailelm.sendKeys("criouser@gmail.com");
        WebElement msgelm =driver.findElement(By.xpath("//input[@placeholder='Message']"));
        msgelm.sendKeys("Testing the contact us page");
        Thread.sleep(3000);
        WebElement btnelm = driver.findElement(By.xpath("//button[text()=' Contact Now']"));
        btnelm.click();

        logStatus("End TestCase",
                "Test Case 10: Verify ContactUs Link: ",
                status ? "PASS" : "FAIL");


        // TODO: CRIO_TASK_MODULE_SYNCHRONISATION -
        return status;
    }

    public static Boolean TestCase11(RemoteWebDriver driver) throws InterruptedException {
        Boolean status = false;
        logStatus("Start TestCase","Test Case 11: Verify Advertisements","DONE");
        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        Thread.sleep(3000);
        status = registration.registerUser("testUser", "abc@123", true);
        Thread.sleep(3000);
        if (!status) {
            logStatus("Step Failure", "User Perform Registration Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 11: Verify Advertisements: ",
                    status ? "PASS" : "FAIL");
            return false;
        }
        lastGeneratedUserName = registration.lastGeneratedUsername;

        Login login = new Login(driver);
        login.navigateToLoginPage();
        Thread.sleep(3000);
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        Thread.sleep(3000);
        if (!status) {
            logStatus("Step Failure", "User Perform Login Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 11: Verify Advertisements: ",
                    status ? "PASS" : "FAIL");
            return false;
        }

        Home homePage = new Home(driver);
        homePage.navigateToHome();
        Thread.sleep(3000);
        status = homePage.searchForProduct("Yonex");
        Thread.sleep(3000);
        homePage.addProductToCart("YONEX Smash Badminton Racquet");
        Thread.sleep(2000);
        homePage.clickCheckout();
        Thread.sleep(3000);

        Checkout checkoutPage = new Checkout(driver);
        checkoutPage.addNewAddress("Addr line 1 addr Line 2 addr line 3");
        Thread.sleep(3000);
        checkoutPage.selectAddress("Addr line 1 addr Line 2 addr line 3");
        Thread.sleep(3000);

        checkoutPage.placeOrder();
        Thread.sleep(3000);

        System.out.println(driver.getCurrentUrl().endsWith("/thanks"));



        
        
        WebElement frame0 = driver.findElement(By.xpath("//*[@id='root']/div/div[2]/div/iframe[1]"));

        driver.switchTo().frame(frame0);
        //System.out.println("The frame0 is displayed: " +frame0.isDisplayed());
        WebElement buynowbtn1 = driver.findElement(By.xpath("//button[text()='Buy Now']"));
        System.out.println("The buynowbtn1 is enabled: " +buynowbtn1.isEnabled());
        if(buynowbtn1.isEnabled()) {
            buynowbtn1.click();
            // driver.getCurrentUrl().endsWith("/checkout");
            driver.navigate().back();
        }
        driver.switchTo().parentFrame();

        WebElement frame1 = driver.findElement(By.xpath("//*[@id='root']/div/div[2]/div/iframe[2]"));
        driver.switchTo().frame(frame1);
        //System.out.println("The frame1 is displayed: " +frame1.isDisplayed());
        WebElement buynowbtn2 = driver.findElement(By.xpath("//button[text()='Buy Now']"));
        System.out.println("The buynowbtn2 is enabled: " +buynowbtn2.isEnabled());
        if(buynowbtn2.isEnabled()) {
            buynowbtn2.click();
            // driver.getCurrentUrl().endsWith("/checkout");
            driver.navigate().back();
        }
        driver.switchTo().parentFrame();

        // driver.switchTo().defaultContent();


        WebElement frame2 = driver.findElement(By.xpath("//*[@id='root']/div/div[2]/iframe"));
        driver.switchTo().frame(frame2);
        //System.out.println("The frame2 is displayed: " +frame2.isDisplayed());

        driver.switchTo().parentFrame();


        logStatus("End TestCase",
                 "Test Case 11: Verify Advertisements: ",
                status ? "PASS" : "FAIL");





        // TODO: CRIO_TASK_MODULE_SYNCHRONISATION -
        return status;
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        int totalTests = 0;
        int passedTests = 0;
        Boolean status;
        RemoteWebDriver driver = createDriver();
        // Maximize and Implicit Wait for things to initailize
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);

        try {
            // Execute Test Case 1
            totalTests += 1;
            status = TestCase01(driver);
            if (status) {
                passedTests += 1;
            }

            System.out.println("");

        // //     //Execute Test Case 2
            totalTests += 1;
            status = TestCase02(driver);
            if (status) {
                passedTests += 1;
            }

            System.out.println("");
        // // //    // Execute Test Case 3
            totalTests += 1;
            status = TestCase03(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

        // //     //Execute Test Case 4
            totalTests += 1;
            status = TestCase04(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

        // // //     //Execute Test Case 5
            totalTests += 1;
            status = TestCase05(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

        // //     // Execute Test Case 6
            totalTests += 1;
            status = TestCase06(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

        // //     // Execute Test Case 7
            totalTests += 1;
            status = TestCase07(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");


        //     // Execute Test Case 8
            totalTests += 1;
            status = TestCase08(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // Execute Test Case 9
            totalTests += 1;
            status = TestCase9(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // // Execute Test Case 10
            totalTests += 1;
            status = TestCase10(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // // Execute Test Case 11
            totalTests += 1;
            status = TestCase11(driver);
            if (status) {
            passedTests += 1;
            }


            System.out.println("");
        } catch (Exception e) {
            throw e;
        } finally {
            // quit Chrome Driver
            driver.quit();

            System.out.println(String.format("%s out of %s test cases Passed ", Integer.toString(passedTests),
                    Integer.toString(totalTests)));
        }

    }
}